# Generated by Django 4.2.5 on 2023-09-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlist', '0002_userprofile_bio_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
