# Generated by Django 4.2.5 on 2023-09-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlist', '0006_rename_friends_friend_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
