# Generated by Django 4.2.5 on 2023-09-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlist', '0009_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
